apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port80
    - port: 443
      targetPort: 443
      name: port443
    - port: 22
      targetPort: 22
      name: port22
  selector:
    app: {{ template "gitlab-ce.name" . }}

