apiVersion: v1
kind: Service
metadata:
  name: {{ template "tomcat.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ template "tomcat.name" . }}

