apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "mariadb.name" . }}

