apiVersion: v1
kind: Service
metadata:
  name: {{ template "ghost.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 2368
      targetPort: 2368
  selector:
    app: {{ template "ghost.name" . }}

