apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 4369
      targetPort: 4369
  selector:
    app: {{ template "rabbitmq.name" . }}

