apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "matomo.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "matomo.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "matomo.name" . }}
    spec:
      containers:
        - name: matomo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: MATOMO_DATABASE_USERNAME
            value: matomo
          - name: MATOMO_DATABASE_HOST
            value: {{ template "matomo.fullname" . }}-database
          - name: MATOMO_DATABASE_PASSWORD
            value: matomo            
          - name: MATOMO_DATABASE_DBNAME
            value: matomo                      
          ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "matomo.fullname" . }}-database
spec:
  selector:
    matchLabels:
      app: {{ template "matomo.name" . }}-database
  template:
    metadata:
      labels:
        app: {{ template "matomo.name" . }}-database
    spec:
      containers:
        - name: matomo-database
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: MYSQL_USER
            value: matomo
          - name: MYSQL_PASSWORD
            value: matomo           
          - name: MYSQL_DATABASE
            value: matomo
          - name: MYSQL_ROOT_PASSWORD
            value: matomo
          ports:
          - containerPort: 3306
