appVersion: 6.1.0
description: "silverpeas 6.1.0  username: SilverAdmin password: SilverAdmin"
name: silverpeas
version: 6.1.0
kewords:
- web
home: https://www.silverpeas.com/
icon: http://10.10.15.32/image/silverpeas-logo.png
