apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port80
    - port: 8080
      targetPort: 8080
      name: port8080
    - port: 443
      targetPort: 443
      name: port443
  selector:
    app: {{ template "traefik.name" . }}

