apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "mediawiki.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "mediawiki.name" . }}
    spec:
      containers:
        - name: mediawiki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}                
          ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}-database
spec:
  selector:
    matchLabels:
      app: {{ template "mediawiki.name" . }}-database
  template:
    metadata:
      labels:
        app: {{ template "mediawiki.name" . }}-database
    spec:
      containers:
        - name: mediawiki-database
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: MYSQL_USER
            value: mediawiki
          - name: MYSQL_PASSWORD
            value: mediawiki           
          - name: MYSQL_DATABASE
            value: mediawiki
          - name: MYSQL_ROOT_PASSWORD
            value: mediawiki
          ports:
          - containerPort: 3306
