apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}-database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ template "mediawiki.name" . }}-database