apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ template "mediawiki.name" . }}