apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgre.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "postgre.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "postgre.name" . }}
    spec:
      containers:
        - name: postgre
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "postgre.fullname" . }}
                key: postgre-password
          - name: POSTGRES_USER
            value: {{ .Values.username | quote }} 
          - name: POSTGRES_DB
            value: {{ .Values.userdatabase | quote }}            
          ports:
          - containerPort: 3306

