apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgre.fullname" . }}
  labels:
    app: {{ template "postgre.name" . }}
    chart: {{ template "postgre.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgre-password: {{ .Values.userpassword | b64enc | quote }}
