apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgre.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "postgre.name" . }}

