apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      name: port8086
  selector:
    app: {{ template "influxdb.name" . }}

