apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "drone.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "drone.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "drone.name" . }}
    spec:
      containers:
      - name: drone
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: DRONE_GITLAB_SERVER
          value: {{ .Values.gitlabserver| quote }}
        - name: DRONE_GITLAB_CLIENT_ID
          value: {{ .Values.gitlabcliid | quote }}
        - name: DRONE_GITLAB_CLIENT_SECRET
          value: {{ .Values.gitlabcliid | quote }}
        - name: DRONE_RPC_SECRET
          value: {{ .Values.gitlabrpccrt | quote }}
        - name: DRONE_SERVER_HOST
          value: {{ .Values.gitlabrpccrt | quote }}
        - name: DRONE_SERVER_PROTO
          value: {{ .Values.gitlabserverproto | quote }}
        ports:
        - containerPort: 80
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /data
          name: drone
      volumes:
      - name: drone
        hostPath:
          path: /data/rancher/drone/

