apiVersion: v1
kind: Service
metadata:
  name: {{ template "drone.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port80
    - port: 443
      targetPort: 443
      name: port443
  selector:
    app: {{ template "drone.name" . }}

