apiVersion: v1
kind: Service
metadata:
  name: {{ template "odoo.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8069
      targetPort: 8069
  selector:
    app: {{ template "odoo.name" . }}