apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jenkins.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "jenkins.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "jenkins.name" . }}
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 8080
        ports:
        - containerPort: 50000
        volumeMounts:
        - mountPath: /etc/gitlab
          name: jenkins
      volumes:
      - name: jenkins
        hostPath:
          path: /data/rancher/jenkins

