apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jekins.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "jekins.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "jekins.name" . }}
    spec:
      containers:
      - name: jekins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 8080
        ports:
        - containerPort: 50000
        volumeMounts:
        - mountPath: /etc/gitlab
          name: jekins
      volumes:
      - name: jekins
        hostPath:
          path: /data/rancher/jekins

