apiVersion: v1
kind: Service
metadata:
  name: {{ template "jekins.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: port8080
    - port: 50000
      targetPort: 50000
      name: port50000
  selector:
    app: {{ template "jekins.name" . }}

