apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: {{ template "mongo.name" . }}
    chart: {{ template "mongo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mongo-password: {{ .Values.userpassword | b64enc | quote }}
