apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "mongo.name" . }}

