apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      name: port8000
    - port: 8443
      targetPort: 8443
      name: port8443
    - port: 8001
      targetPort: 8001
      name: port8001
    - port: 8444
      targetPort: 8444
      name: port8444
  selector:
    app: {{ template "kong.name" . }}