apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ template "kong.name" . }}-database