apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ template "redis.name" . }}

