apiVersion: v1
kind: Service
metadata:
  name: {{ template "memcached.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: {{ template "memcached.name" . }}

