apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ template "grafana.name" . }}

