apiVersion: v1
kind: Service
metadata:
  name: {{ template "silverpeas.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ template "silverpeas.name" . }}