apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-web
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ template "zabbix.name" . }}-web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-server
spec:
  type: NodePort
  ports:
    - port: 10051
      targetPort: 10051
  selector:
    app: {{ template "zabbix.name" . }}-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ template "zabbix.name" . }}-database