apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: {{ template "elasticsearch.name" . }}

